-- Insert sample data into the ideas table
INSERT INTO ideas (
  title, 
  description, 
  problem, 
  solution, 
  category, 
  subcategories, 
  type, 
  "sourceName", 
  "sourceLogo", 
  "sourceDate", 
  "sourceLink", 
  "startTime", 
  "endTime", 
  clicks
) VALUES 
(
  'AI-Powered Recipe Generator',
  'Generate personalized recipes based on dietary restrictions, available ingredients, and taste preferences using machine learning.',
  'Home cooks struggle to create meals with ingredients they have on hand, often leading to food waste and repetitive meals. People with dietary restrictions face even greater challenges finding suitable recipes that match their needs and available ingredients.',
  'An AI-powered mobile app that uses computer vision to identify ingredients in your pantry, then generates personalized recipes based on dietary restrictions, taste preferences, and nutritional goals. The app learns from user feedback to improve recommendations over time.',
  'Food & Drink',
  ARRAY['AI', 'Food', 'Health', 'Mobile App'],
  'Mobile App Business',
  'FoodTech Weekly',
  '/placeholder.svg?height=40&width=40',
  '2024-06-10',
  'https://foodtechweekly.com/ai-recipe-generator-trend',
  '00:15:30',
  '00:17:45',
  1247
),
(
  'Virtual Plant Care Assistant',
  'AR app that helps users identify plant diseases, watering schedules, and optimal growing conditions through camera recognition.',
  'Plant enthusiasts, especially beginners, struggle to properly care for their plants due to lack of knowledge about specific plant needs, disease identification, and optimal growing conditions. This leads to high plant mortality rates and discourages people from gardening.',
  'An AR-enabled mobile app that uses camera recognition to identify plants, diagnose diseases, and provide personalized care schedules. Users can scan their plants to get real-time health assessments, watering reminders, and treatment recommendations.',
  'Lifestyle',
  ARRAY['AR', 'Plants', 'Health', 'Education'],
  'Mobile App Business',
  'GreenTech Innovators',
  '/placeholder.svg?height=40&width=40',
  '2024-06-05',
  'https://greentechinnovators.com/plant-care-ar-future',
  '00:22:10',
  '00:24:55',
  892
),
(
  'Micro-Learning Language Exchange',
  '5-minute daily language exchange sessions with native speakers, gamified with streak tracking and cultural insights.',
  'Traditional language learning apps lack real conversation practice with native speakers, while existing language exchange platforms require long time commitments that busy professionals can''t maintain. Most people abandon language learning due to lack of consistent practice opportunities.',
  'A platform that connects language learners for 5-minute daily video exchanges with native speakers. Gamified with streak tracking, cultural insights, and AI-powered conversation prompts to keep sessions engaging and educational.',
  'Education',
  ARRAY['Education', 'Social', 'Gamification', 'Language'],
  'Community',
  'EdTech Pioneers',
  '/placeholder.svg?height=40&width=40',
  '2024-06-01',
  'https://edtechpioneers.com/micro-learning-revolution',
  '00:08:45',
  '00:11:20',
  2156
),
(
  'Local Skill Bartering Platform',
  'Connect neighbors to trade skills and services without money - coding for cooking, design for gardening, etc.',
  'Many people have valuable skills but lack the cash to pay for services they need. Traditional service marketplaces require monetary transactions, excluding those who prefer skill-based exchanges. Communities lack efficient ways to connect neighbors with complementary skills.',
  'A hyperlocal platform where neighbors can trade skills and services without money. Features include skill verification, rating systems, and smart matching algorithms. Users can offer coding lessons for cooking classes, design work for gardening help, etc.',
  'Social',
  ARRAY['Social', 'Community', 'Skills', 'Local'],
  'Marketplace',
  'Community Builders',
  '/placeholder.svg?height=40&width=40',
  '2024-05-28',
  'https://communitybuilders.com/skill-bartering-future',
  '00:14:00',
  '00:16:30',
  634
),
(
  'AI Meeting Summarizer',
  'Automatically transcribe, summarize, and extract action items from video calls with smart categorization and follow-up reminders.',
  'Remote workers spend 23 hours per week in meetings, with poor note-taking leading to missed action items and unclear follow-ups. Manual meeting summaries are time-consuming and often incomplete, causing project delays and miscommunication.',
  'An AI-powered tool that automatically transcribes, summarizes, and extracts action items from video calls. Features smart categorization, follow-up reminders, and integration with project management tools. Works across Zoom, Teams, and Google Meet.',
  'Productivity',
  ARRAY['AI', 'Productivity', 'Business', 'SaaS'],
  'SaaS',
  'ProductivityPro',
  '/placeholder.svg?height=40&width=40',
  '2024-06-12',
  'https://productivitypro.com/ai-meeting-revolution',
  '00:09:15',
  '00:12:00',
  3421
),
(
  'Sustainable Fashion Tracker',
  'Track the environmental impact of your wardrobe, get sustainable alternatives, and connect with eco-conscious fashion communities.',
  'Consumers want to make sustainable fashion choices but lack transparency about environmental impact. Fast fashion contributes to 10% of global carbon emissions, yet shoppers have no easy way to track their wardrobe''s environmental footprint or find sustainable alternatives.',
  'An app that tracks your wardrobe''s environmental impact using barcode scanning and brand databases. Provides sustainable alternatives, connects users with eco-conscious communities, and gamifies sustainable fashion choices with challenges and rewards.',
  'Lifestyle',
  ARRAY['Sustainability', 'Fashion', 'Environment', 'Social'],
  'Content Business',
  'EcoStyle Magazine',
  '/placeholder.svg?height=40&width=40',
  '2024-05-20',
  'https://ecostylemagazine.com/sustainable-fashion-tech',
  '00:11:30',
  '00:14:15',
  1089
),
(
  'Voice-Controlled Smart Home Hub',
  'Open-source alternative to Alexa/Google Home with privacy-first approach and local processing capabilities.',
  'Current smart home assistants like Alexa and Google Home raise privacy concerns by constantly listening and sending data to cloud servers. Tech-savvy users want smart home control without sacrificing privacy or depending on internet connectivity.',
  'An open-source, privacy-first smart home hub that processes voice commands locally without internet dependency. Features include offline operation, encrypted communications, and compatibility with major smart home protocols like Zigbee and Z-Wave.',
  'Technology',
  ARRAY['IoT', 'Privacy', 'Open Source', 'Hardware'],
  'API Product',
  'Open Tech Alliance',
  '/placeholder.svg?height=40&width=40',
  '2024-05-15',
  'https://opentechalliance.org/privacy-smart-home',
  '00:16:45',
  '00:19:30',
  1876
),
(
  'Freelancer Time Auction',
  'Reverse marketplace where freelancers auction their available time slots, clients bid on preferred time windows.',
  'Freelancers struggle with unpredictable schedules and pricing their time competitively, while clients face difficulty finding available freelancers for urgent projects. Traditional freelance platforms don''t optimize for time-sensitive matching.',
  'A reverse marketplace where freelancers auction their available time slots, and clients bid on preferred time windows. Features real-time availability, dynamic pricing based on urgency, and smart matching algorithms for optimal freelancer-client pairing.',
  'Business',
  ARRAY['Freelancing', 'Marketplace', 'Time Management', 'Business'],
  'Marketplace',
  'Future of Work',
  '/placeholder.svg?height=40&width=40',
  '2024-05-10',
  'https://futureofwork.com/freelancer-time-auction',
  '00:20:00',
  '00:22:45',
  756
),
(
  'Developer API Analytics Dashboard',
  'Comprehensive analytics platform for API developers to track usage, performance, and monetization metrics across multiple APIs.',
  'API developers lack comprehensive analytics to understand usage patterns, optimize performance, and maximize monetization. Existing tools are fragmented, expensive, or provide limited insights across multiple APIs and platforms.',
  'A unified analytics platform for API developers to track usage, performance, and monetization metrics across multiple APIs. Features include real-time monitoring, predictive analytics, revenue optimization suggestions, and developer-friendly dashboards.',
  'Technology',
  ARRAY['Analytics', 'API', 'Developer Tools', 'Dashboard'],
  'Data Business',
  'DevTools Central',
  '/placeholder.svg?height=40&width=40',
  '2024-06-13',
  'https://devtoolscentral.com/api-analytics-future',
  '00:07:30',
  '00:10:15',
  445
),
(
  'Startup Directory & Resources Hub',
  'Curated directory of startups, investors, accelerators, and resources with advanced filtering and networking features.',
  'Entrepreneurs struggle to discover relevant startups, investors, and resources due to fragmented information across multiple platforms. Networking in the startup ecosystem is inefficient, and finding the right connections often depends on luck rather than systematic discovery.',
  'A comprehensive directory of startups, investors, accelerators, and resources with advanced filtering, networking features, and AI-powered matching. Includes startup profiles, funding tracking, event listings, and a recommendation engine for relevant connections.',
  'Business',
  ARRAY['Startups', 'Directory', 'Networking', 'Resources'],
  'Directory',
  'Startup Ecosystem',
  '/placeholder.svg?height=40&width=40',
  '2024-06-11',
  'https://startupecosystem.com/directory-revolution',
  '00:12:45',
  '00:15:30',
  2890
),
(
  'Personal Finance AI Coach',
  'AI-powered personal finance assistant that analyzes spending patterns and provides personalized budgeting advice.',
  'Most people struggle with personal finance management due to complex financial products, lack of personalized advice, and expensive financial advisors. Traditional budgeting apps provide basic tracking but lack intelligent insights and proactive coaching.',
  'An AI-powered personal finance coach that analyzes spending patterns, provides personalized budgeting advice, and offers proactive financial coaching. Features include expense categorization, goal tracking, investment suggestions, and behavioral nudges for better financial habits.',
  'Business',
  ARRAY['AI', 'Finance', 'Personal', 'Coaching'],
  'SaaS',
  'FoodTech Weekly',
  '/placeholder.svg?height=40&width=40',
  '2024-04-15',
  'https://foodtechweekly.com/ai-finance-coach',
  '00:18:00',
  '00:20:45',
  1567
),
(
  'Remote Team Culture Builder',
  'Platform to help remote teams build stronger culture through virtual activities, team building, and communication tools.',
  'Remote teams struggle to build strong company culture and meaningful connections without in-person interactions. Traditional team building activities don''t translate well to virtual environments, leading to decreased engagement and higher turnover rates.',
  'A platform designed specifically for remote team culture building through virtual activities, team building exercises, and communication tools. Features include culture assessment tools, virtual coffee chats, team challenges, and analytics to measure culture health.',
  'Business',
  ARRAY['Remote Work', 'Team Building', 'Culture', 'Communication'],
  'SaaS',
  'ProductivityPro',
  '/placeholder.svg?height=40&width=40',
  '2024-03-20',
  'https://productivitypro.com/remote-culture-building',
  '00:21:15',
  '00:24:00',
  923
);
